version: "2.3"

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - laravel
    healthcheck:
      test: ["CMD-SHELL", 'mysql -uroot --database=laravel --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - laravel

networks:
  laravel:
    driver: bridge


